fixtures:
  forge_modules:
    stdlib:      "puppetlabs/stdlib"
    artifactory: "autostructure/artifactory"
    java:        "puppetlabs/java"
    wget:        "puppet/wget"
  symlinks:
    artifactory_pro: "#{source_dir}"
